title: Wenqi Deng's Homepage
page-top-title: Wenqi Deng
top-section-bg-text: Computer Science
home-subtitle: Wenqi Deng&ensp;|&ensp;邓文骐
copyright-text: '&copy; Sen Li 2023-2026. All Rights Reserved.'
